[package]
name = "ddbg-tui"
version.workspace = true
edition.workspace = true
description = "Terminal user interface for ddbg"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
ddbg-core.workspace = true
ddbg-cli.workspace = true
anyhow.workspace = true
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
tokio.workspace = true
syntect.workspace = true

[dev-dependencies]
ddbg-test.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true
