[package]
name = "ddbg-core"
version.workspace = true
edition.workspace = true
description = "Core debugger session logic for ddbg"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
ddbg-dap.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
quickcheck.workspace = true
quickcheck_macros.workspace = true
