[package]
name = "ddbg-test"
version.workspace = true
edition.workspace = true
description = "Test discovery and debugging for ddbg"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
ddbg-core.workspace = true
ddbg-project.workspace = true
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
