[package]
name = "ddbg-driver"
version.workspace = true
edition.workspace = true
description = "Test driver for ddbg"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
ddbg-core.workspace = true
ddbg-cli.workspace = true
ddbg-test.workspace = true
anyhow.workspace = true
tokio.workspace = true

[dev-dependencies]
ddbg-dap.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
