[package]
name = "ddbg-dap"
version.workspace = true
edition.workspace = true
description = "Debug Adapter Protocol client for ddbg"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"

[dependencies]
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
